Floating IP sync improvements
costela/hcloud-ip-floater pull request #11
Opened 2020-06-14 09:30 UTC by eplightning

During my tests I have encountered issue where the controller would send IP assignment requests to Hetzner API even though the floating IP was already attached to the correct server. This would occur every 5 minutes.

I don't know if this has any other negative side-effects but at the very least it's a couple of redundant API calls and notifications in Hetzner Cloud Console (every floating IP assignement API call creates new notification there, no matter if this actually changed anything or not).

After some investigation it turned out the culprit was `syncFloatingIPs` function which didn't update old FIP's in the `fips` map. The map was only updated when FIP ID's changed but not when Server ID's changed. Since the map wasn't updated the `Reconcile` function would then do the floating IP assignment API call - and continue to do it every 5 minutes.

This PR fixes this bug by modifying the `syncFloatingIPs` to take into the account Server ID's as well. There are also changes that should reduce amount of redundant reconciles caused by that function. 

I'm always open to suggestions if you don't like some changes in this PR. :)

2020-06-15 22:01 UTC, costela requested changes
hi @eplightning

Big thanks for the PR! This is a definite improvement.

I just made a couple of minor comments. If you could take a look at them, we can get this merged ASAP.

2020-06-15 22:01 UTC, costela commented on internal/fipcontroller/fipcontroller.go
> +		if oldFIP == nil || fc.fipChanged(oldFIP, fip) {
a bit of bikeshedding: can we maybe rename this to `!fipEquals(oldFIP, fip)`? (without the receiver)

2020-06-15 22:01 UTC, costela commented on internal/fipcontroller/fipcontroller.go
> +		} else if (oldFIP.Server != nil && oldFIP.Server.Name != fc.attachments[ip]) || (oldFIP.Server == nil && fc.attachments[ip] != "") {
Maybe this would be more readable if we added another little helper:
```go
func fipServerName(fip *hcloud.FloatingIP) string {
	if fip.Server != nil {
		return fip.Server.Name
	}
	return ""
}
```

Then this could become:
```suggestion
		} else if fipServerName(oldFIP) != fc.attachments[ip] {
```

(but don't get me wrong: the original code was already pretty unreadable; that's on me.)

2020-06-15 22:01 UTC, costela commented on internal/fipcontroller/fipcontroller.go
> +	return false
if we add the helper suggested above, this whole function could become 
```suggestion
	return oldFIP.ID != newFIP.ID || fipServerName(oldFIP) != fipServerName(newFIP) 
```

This should work because hcloud ensures server names are unique in a project.
It has the not-so-nice property of triggering a reconciliation on server renaming, but renamings would break a lot of other things as well (like k8s itself), so I think it's an acceptable simplification.

2020-06-16 15:54 UTC, eplightning commented on internal/fipcontroller/fipcontroller.go
> +		if oldFIP == nil || fc.fipChanged(oldFIP, fip) {
Not sure why I even made it a function with receiver. Guess I just didn't touch Go for too long : )

Fixed and renamed

2020-06-16 15:55 UTC, eplightning commented on internal/fipcontroller/fipcontroller.go
> +		} else if (oldFIP.Server != nil && oldFIP.Server.Name != fc.attachments[ip]) || (oldFIP.Server == nil && fc.attachments[ip] != "") {
Done. Yeah this helper made it way more readable now.

2020-06-16 16:10 UTC, eplightning commented on internal/fipcontroller/fipcontroller.go
> +	return false
That would require additional API calls, server name is empty for newFIP - server objects returned by `hcloudClient.FloatingIP().AllWithOpts` don't have it.

I'm fine with changing that if you think it's worth it regardless .

2020-06-16 22:20 UTC, costela commented on internal/fipcontroller/fipcontroller.go
> +	return false
ah yes, good point. Then I guess we'll have to live with the bigger function. Not the end of the world.

2020-06-16 22:23 UTC, costela approved these changes

2020-06-16 22:23 UTC, merged

2020-06-16 22:23 UTC, costela commented
Thanks again for the work! :+1: